SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('develop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/develop/urls.py
from django.urls import path
from .views import *

app_name = "develop"

urlpatterns = [
    path('', list_idea, name="list_idea"),

    path('tools', list_tool, name="list_tool"),
    path('create/tool', create_tool, name="create_tool"),
    path('tool/<int:pk>', show_tool, name="show_tool"),
    path('edit/tool/<int:pk>', edit_tool, name="edit_tool"),
    path('delete/tool/<int:pk>', delete_tool, name="delete_tool"),

    path('create/idea', create_idea, name="create_idea"),
    path('idea/<int:pk>', show_idea, name="show_idea"),
    path('edit/idea/<int:pk>', edit_idea, name="edit_idea"),
    path('delete/idea/<int:pk>', delete_idea, name="delete_idea"),

    path('interest/', edit_interest, name="interest")
]

SWIDEA_SITE/develop/models.py
from django.db import models

class Tool(models.Model):
    name = models.CharField(">> 이름", max_length = 20)
    kind = models.CharField(">> 종류", max_length = 20)
    description = models.TextField(">> 개발툴 설명")
    
    def __str__(self):
        return self.name

class Idea(models.Model):
    title = models.CharField(">> 아이디어명", max_length = 20)
    image = models.ImageField(">> 대표 사진", blank=True)
    content = models.TextField(">> 아이디어 설명")
    interest = models.IntegerField(">> 아이디어 관심도")
    devtool = models.ForeignKey(Tool, on_delete=models.CASCADE, related_name="ideas", verbose_name=">> 예상 개발툴")

    def __str__(self):
        return f"[{self.devtool.name}] {self.title}"

SWIDEA_SITE/develop/forms.py
from django import forms
from .models import *

class ToolForm(forms.ModelForm):
    class Meta:
        model = Tool
        fields = "__all__"

class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = "__all__"

SWIDEA_SITE/develop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def list_idea(request):
    objects = Idea.objects.all()   
    return render(request, "develop/list.html", {"objects":objects, "idea_yes":True})

def show_idea(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    return render(request, "develop/show.html", {"idea":idea, "idea_yes":True})

def create_idea(request):
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save()
            return redirect("develop:show_idea", instance.id)
    else:
        form = IdeaForm()
        return render(request, "develop/form_idea.html", {"form":form})

def edit_idea(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES, instance=idea)
        if form.is_valid():
            form.save()
        return redirect("develop:show_idea", pk)
    else:
        form = IdeaForm(instance=idea)
        ctx = {"form":form, "pk":pk}
        return render(request, template_name="develop/form_idea.html", context=ctx)

def delete_idea(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    idea.delete()
    return redirect("/")

def list_tool(request):
    objects = Tool.objects.all()
    return render(request, "develop/list.html", {"objects":objects})

def show_tool(request, pk):
    tool = get_object_or_404(Tool, id=pk)
    return render(request, "develop/show.html", {"tool":tool})

def create_tool(request):
    if request.method == "POST":
        form = ToolForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect("develop:show_tool", instance.id)
    else:
        form = ToolForm()
        return render(request, "develop/form_tool.html", {"form":form})

def edit_tool(request, pk):
    tool = get_object_or_404(Tool, id=pk)
    if request.method == "POST":
        form = ToolForm(request.POST, instance=tool)
        if form.is_valid():
            form.save()
        return redirect("develop:show_tool", pk)
    else:
        form = ToolForm(instance=tool)
        ctx = {"form":form, "pk":pk}
        return render(request, template_name="develop/form_tool.html", context=ctx)

def delete_tool(request, pk):
    tool = get_object_or_404(Tool, id=pk)
    tool.delete()
    return redirect("develop:list_tool")

@csrf_exempt
def edit_interest(request):
    req = json.loads(request.body)
    idea_id = req["id"]
    btn_type = req["type"]
    idea = get_object_or_404(Idea, id=idea_id)

    if btn_type == "plus":
        idea.interest += 1
    else:
        idea.interest -= 1
    idea.save()

    return JsonResponse({"id":idea_id, "type":btn_type})

SWIDEA_SITE/develop/templates/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} My SW Idea Management {% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'css/develop.css' %}" /> -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </head>
  <body class="px-5">
    <header>
      <nav class="d-flex w-100 justify-content-between">
        <div class="nav__column">
          <a href="/">
            <h1>My SW Idea Management</h1>
          </a>
        </div>
        <div class="nav__column d-flex">
          <a href="{% url 'develop:create_idea' %}" class="me-2"
            >아이디어 등록</a
          ><a href="/" class="me-2">아이디어 관리</a
          ><a href="{% url 'develop:create_tool' %}" class="me-2">개발툴 등록</a
          ><a href="/tools">개발툴 관리</a>
        </div>
      </nav>
    </header>
    {% block content %} {% endblock %}
  </body>
</html>

SWIDEA_SITE/develop/templates/develop/form_idea.html
{% extends "base.html" %} {% load bootstrap5 %} {% bootstrap_css %} {%
bootstrap_javascript %} {% block title %} {% if pk %} Edit Idea {% else %}
Register Idea {% endif %} {% endblock %} {% block content %} {% if pk %}
<h4 class="text-center">Edit idea</h4>
{% else %}
<h4 class="text-center">Register idea</h4>
{% endif %}
<div class="d-flex justify-content-center w-100">
  <form action="" method="POST" enctype="multipart/form-data" class="w-50">
    {% csrf_token %}
    <table>
      {% bootstrap_form form %}
    </table>
    {% if pk %}
    <button type="submit" class="btn btn-primary">Update</button>
    {% else %}
    <button type="submit" class="btn btn-success">Register</button>
    {% endif %}
  </form>
</div>
{% endblock %}

SWIDEA_SITE/develop/templates/develop/form_tool.html
{% extends "base.html" %} {% load bootstrap5 %} {% bootstrap_css %} {%
bootstrap_javascript %} {% block title %} {% if pk %} Edit Devtool {% else %}
Register Devtool {% endif %} {% endblock %} {% block content %} {% if pk %}
<h4 class="text-center">Edit Devtool</h4>
{% else %}
<h4 class="text-center">Register Devtool</h4>
{% endif %}
<div class="d-flex justify-content-center w-100">
  <form action="" method="POST" class="w-50">
    {% csrf_token %}
    <table>
      {% bootstrap_form form %}
    </table>
    {% if pk %}
    <button type="submit" class="btn btn-primary">Update</button>
    {% else %}
    <button type="submit" class="btn btn-success">Register</button>
    {% endif %}
  </form>
</div>
{% endblock %}

SWIDEA_SITE/develop/templates/develop/list.html
{% extends "base.html" %} {% load static %} {% block content %}
<h2 class="text-center">
  {% if idea_yes %}Idea{% else %}DevTool{% endif %} List
</h2>
<div class="object-container d-flex">
  {% for object in objects %}
  <div
    class="object me-4 border border-2 border-light d-flex flex-column align-items-center"
    data-id="{{object.id}}"
  >
    {% if idea_yes %} {% if object.image %}
    <img src="{{object.image.url}}" width="150" height="225" />
    {% else %}
    <img src="https://picsum.photos/seed/{{object.id}}/150/225" />
    {% endif %}
    <a href="{% url 'develop:show_idea' object.id%}" class="title">
      <h3>{{object.title}}</h3>
    </a>
    <div>예상 개발툴 : {{object.devtool}}</div>
    <div>
      아이디어 관심도 : <span class="interest">{{object.interest}}</span>
      <button
        class="plus btn btn-sm btn-warning me-2 text-white fw-bold plus-btn"
        onclick="onClickInterest({{object.id}}, 'plus')"
      >
        +</button
      ><button
        class="minus btn btn-sm btn-warning text-white fw-bold minus-btn"
        onclick="onClickInterest({{object.id}}, 'minus')"
      >
        -
      </button>
    </div>
    <script src="{% static 'ajax.js' %}"></script>
    {% else %}
    <a href="{% url 'develop:show_tool' object.id%}"
      ><h3>{{object.name}}</h3>
    </a>
    <h5>{{object.kind}}</h5>
    <div class="text-center">{{object.description}}</div>
    {% endif %}
  </div>
  {% endfor %} {% endblock %}
</div>

SWIDEA_SITE/develop/templates/develop/show.html
{% extends "base.html" %} {% block title %} {% if idea_yes %} {{idea.title}}
{%else %} {{tool.name}} {% endif %} {% endblock %} {%block content %} <br />
{%if idea_yes %}
<h4 class="text-center">Idea Detail</h4>
<div class="idea d-flex">
  <div class="idea__img me-5">
    {% if idea.image %}
    <img src="{{idea.image.url}}" width="150" height="225" />
    {% else %}
    <img src="https://picsum.photos/seed/{{idea.id}}/150/225" />
    {% endif %}
  </div>
  <div class="idea__content">
    <h2>{{idea.title}}</h2>
    <ol>
      <li>아이디어 관심도 : {{idea.interest}}</li>
      <li>
        예상 개발툴 :
        <a href="{% url 'develop:show_tool' pk=idea.devtool.id %}"
          >{{idea.devtool}}</a
        >
      </li>
      <li>아이디어 설명 : {{idea.content}}</li>
    </ol>
  </div>
</div>
<div class="btn-container d-flex justify-content-center w-100">
  <a href="{% url 'develop:delete_idea' idea.id %}" class="btn btn-danger"
    >삭제</a
  >
  <a href="/" class="btn btn-white">목록</a>
  <a href="{% url 'develop:edit_idea' idea.id %}" class="btn btn-primary"
    >수정</a
  >
</div>

{% else %}
<h4 class="text-center">DevTool Detail</h4>
<div class="tool">
  <div class="tool__content">
    <h2>{{tool.name}}</h2>
    <p>✔ {{tool.kind}}</p>
    <p>👉 {{tool.description}}</p>
  </div>
  <div class="tool__ideas">
    <h5>> 만들 수 있는 SW 목록</h5>
    <ul>
      {% for idea in tool.ideas.all %}
      <li>
        <a href="{% url 'develop:show_idea' pk=idea.id %}">{{idea.title}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
<div class="btn-container d-flex justify-content-center w-100">
  <a href="{% url 'develop:delete_tool' tool.id %}" class="btn btn-danger"
    >삭제</a
  >
  <a href="/tools" class="btn btn-white">목록</a>
  <a href="{% url 'develop:edit_tool' tool.id %}" class="btn btn-primary"
    >수정</a
  >
</div>
{% endif %} {% endblock %}