myMovieReviews/CRUDproject/CRUDproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls'))
]

myMovieReviews/CRUDproject/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path('', views.show_list, name="list"),
    path('order_by_<str:order>/', views.show_list, name="ordered_list"),
    path('write/', views.write_review, name="write"),
    path('<int:pk>/', views.show_detail, name="detail"),
    path('update/<int:pk>/', views.update_review, name="update"),
    path('delete/<int:pk>/', views.delete_review, name="delete")
]

myMovieReviews/CRUDproject/reviews/models.py
from django.db import models
from datetime import *

class Review(models.Model):
    title = models.CharField(verbose_name='제목', max_length=100)

    YEAR_CHOICES = [(y,y) for y in range(1950, (datetime.now().year+1))]
    year = models.PositiveSmallIntegerField(verbose_name='개봉년도', choices=YEAR_CHOICES)
    director = models.CharField(verbose_name='감독', max_length=100)
    actor = models.CharField(verbose_name='주연', max_length=200)

    GENRE_CHOICES = [
        ('ACT', '액션'),
        ('COM', '코미디'),
        ('DR', '드라마'),
        ('RO', '로맨스'),
        ('HO', '공포'),
        ('TH', '스릴러'),
        ('SF', 'SF'),
        ('FAN', '판타지'),
        ('ANI', '애니메이션'),
        ('DOC', '다큐멘터리'),
        ('IN', '독립영화'),
        ('ETC', '기타')
    ]
    genre = models.CharField(verbose_name='장르', max_length=3, choices=GENRE_CHOICES)
    running_time = models.PositiveSmallIntegerField(verbose_name='러닝타임 (분)')

    RATING_CHOICES = [(0.5*i, 0.5*i) for i in range(1, 11)]
    rating = models.FloatField(verbose_name='별점', choices=RATING_CHOICES)
    review = models.TextField(verbose_name='리뷰')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def running_time_by_hour(self):
        h, m = "", ""
        if self.running_time//60:
            h = f"{self.running_time//60}시간 "
        if self.running_time%60:
            m = f"{self.running_time%60}분"
        return h+m

myMovieReviews/CRUDproject/reviews/forms.py
from django import forms
from .models import Review
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

myMovieReviews/CRUDproject/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .forms import ReviewForm

def show_list(request, order=None):
    if order == None:
        reviews = Review.objects.all()
    elif order == "h-rating":
        reviews = Review.objects.all().order_by("-rating")
    elif order == "l-rating":
        reviews = Review.objects.all().order_by("rating")
    elif order == "latest":
        reviews = Review.objects.all().order_by("-created_at")
    elif order == "l-runtime":
        reviews = Review.objects.all().order_by("-running_time")
    elif order == "s-runtime":
        reviews = Review.objects.all().order_by("running_time")   
    else:
        return redirect("/")       
    ctx = {"reviews":reviews}
    return render(request, template_name="reviews/list.html", context=ctx)

def write_review(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = ReviewForm()
        ctx = {"form":form}
        return render(request, template_name="reviews/write.html", context=ctx)

def show_detail(request, pk):
    review = get_object_or_404(Review, id=pk)
    ctx = {"review":review}
    return render(request, template_name="reviews/detail.html", context=ctx)

def update_review(request, pk):
    review = get_object_or_404(Review, id=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, instance = review)
        if form.is_valid():
            form.save()
        return redirect("reviews:detail", pk)
    else:
        form = ReviewForm(instance = review)
        ctx = {"form":form, "pk":pk}
        return render(request, template_name="reviews/write.html", context=ctx)

def delete_review(request, pk):
    review = get_object_or_404(Review, id=pk)
    review.delete()
    return redirect("/")

myMovieReviews/CRUDproject/reviews/templates/reviews/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>My Movie Reviews 🎞</title>
    {% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}" />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://kit.fontawesome.com/6a23cd815d.js"
      crossorigin="anonymous"
    ></script>
    {% block script %} {% endblock %}
  </head>
  <body class="pb-5">
    <header>
      <a href="/">
        <h1 class="d-inline-block">
          <img
            src="https://i.ibb.co/xjPT5WS/logo.png"
            alt="My Movie Reviews"
            class="py-3"
          />
        </h1>
      </a>
    </header>
    {% block content %} {% endblock %}
  </body>
</html>

myMovieReviews/CRUDproject/reviews/templates/reviews/detail.html
{% extends 'reviews/base.html' %} {% load static %} {% block script %}
<script defer src="{% static 'js/reviews.js' %}"></script>
{% endblock %} {% block title %} <title>{{review.title}}</title> {% endblock %}
{% block content %}

<div class="btn-container d-flex justify-content-end mb-4">
  <a
    href="{% url 'reviews:update' review.id %}"
    class="fs-4 fw-bold btn btn-danger text-white me-4"
    >Edit</a
  >
  <a
    href="{% url 'reviews:delete' review.id %}"
    class="fs-4 fw-bold btn btn-danger text-white"
    >Delete</a
  >
</div>

<section id="detail">
  <article class="review py-5 mx-auto">
    <div
      class="horizontal-container d-flex justify-content-between align-items-center"
    >
      <div class="review_content">
        <h2 class="review_title fs-1 mb-5 lh-base">{{review.title}}</h2>

        <div class="review_details d-flex flex-column fs-2">
          <div class="review_year">
            <span class="fw-bold text-secondary me-3">개봉년도</span
            ><span>{{review.year}}</span>
          </div>
          <div class="review_director">
            <span class="fw-bold text-secondary me-3 lh-base">감독</span
            ><span class="lh-base">{{review.director}}</span>
          </div>
          <div class="review_actorr">
            <span class="fw-bold text-secondary me-3">주연</span
            ><span class="lh-base">{{review.actor}}</span>
          </div>
          <div class="review_genre">
            <span class="fw-bold text-secondary me-3">장르</span
            ><span>{{review.get_genre_display}}</span>
          </div>
          <div class="review_running-time">
            <span class="fw-bold text-secondary me-3">러닝타임</span
            ><span>{{review.running_time_by_hour}}</span>
          </div>
          <div class="review_rating">
            <span class="fw-bold text-secondary me-3">별점</span
            ><span class="stars text-warning me-2">{{review.rating}}</span
            ><span>({{review.rating}})</span>
          </div>
        </div>
      </div>

      <div class="review_img ms-5">
        <img src="https://picsum.photos/300/400" alt="{{review.title}}" />
      </div>
    </div>

    <div class="review_review mt-5 fs-2">
      <span class="fw-bold text-secondary">리뷰</span>
      <p class="mt-3 lh-base">{{review.review}}</p>
    </div>
  </article>
</section>
{% endblock %}

myMovieReviews/CRUDproject/reviews/templates/reviews/list.html
{% extends 'reviews/base.html' %} {% load static %} {% block script %}
<script defer src="{% static 'js/reviews.js' %}"></script>
{% endblock %} {% block content %}

<div class="d-flex justify-content-end mb-3">
  <a href="/write" class="write-btn fs-4 fw-bold btn btn-danger text-white"
    >Leave a review ✨</a
  >
</div>
<div class="order-container d-flex justify-content-end mb-5">
  <select class="form-select w-auto" aria-label="Default select example">
    <option selected>--- 정렬 기준 ---</option>
    <option value="h-rating">높은 별점</option>
    <option value="l-rating">낮은 별점</option>
    <option value="latest">최근 등록일</option>
    <option value="old">오래된 등록일</option>
    <option value="l-runtime">긴 상영 시간</option>
    <option value="s-runtime">짧은 상영 시간</option>
  </select>
</div>

<section id="reviews" class="d-flex flex-wrap">
  {% for review in reviews %}
  <article class="review d-flex flex-column align-items-center p-4">
    <div class="review_img">
      <img src="https://picsum.photos/200/300" alt="{{review.title}}" />
    </div>

    <a href="{% url 'reviews:detail' review.id %}"
      ><h2 class="review_title fs-2 my-4 text-center lh-base">
        {{review.title}}
      </h2></a
    >

    <div class="review_details d-flex flex-column align-items-center">
      <div class="review_year">
        <span class="fw-bold text-secondary me-2">개봉년도</span
        ><span>{{review.year}}</span>
      </div>
      <div class="review_genre">
        <span class="fw-bold text-secondary me-2">장르</span
        ><span>{{review.get_genre_display}}</span>
      </div>
      <div class="review_running-time">
        <span class="fw-bold text-secondary me-2">러닝타임</span
        ><span>{{review.running_time_by_hour}}</span>
      </div>
      <div class="review_rating">
        <span class="stars text-warning me-2">{{review.rating}}</span
        ><span>({{review.rating}})</span>
      </div>
    </div>
  </article>
  {% endfor %}
</section>
{% endblock %}

myMovieReviews/CRUDproject/reviews/templates/reviews/write.html
{% extends 'reviews/base.html' %} {% load bootstrap5 %} {% bootstrap_css %} {%
bootstrap_javascript %} {% block title %} {% if not pk %}
<title>Leave a review ✏</title> {% else %} <title>Edit your review ✏</title>
{% endif %} {% endblock %} {% block content %}
<form action="" method="POST" class="w-50 mx-auto fs-4">
  {% csrf_token %}
  <table>
    {% bootstrap_form form %}
  </table>

  <div class="d-flex justify-content-center">
    {% if pk %}
    <button type="submit" class="fs-4 fw-bold btn btn-danger text-white mt-4">
      Save changes ✔
    </button>
    {% else %}
    <button type="submit" class="fs-4 fw-bold btn btn-danger text-white mt-4">
      Upload ✔
    </button>
    {% endif %}
  </div>
</form>
{% endblock %}